### ISSUE TITLE
owncloud-docker + compose + postgresql

### ISSUE THREAD

**Issue by ohugues** [tkock/owncloud-docker-compose#1]
Here is my compose file to use with owncloud docker, compose and official postgresql image that seems to work:

     nginx:
       image: jwilder/nginx-proxy:latest
       environment:
         - VIRTUAL_PROTO=https
       ports:
         - "443:443"
       volumes:
         - /var/run/docker.sock:/tmp/docker.sock
         - /srv/docker/nginx/certs:/etc/nginx/certs
     
     owncloud:
       image: l3iggs/owncloud:latest
       links:
         - postgresowncloud:postgres
       environment:
         - VIRTUAL_HOST=owncloud.mydomain.com
         - TARGET_SUBDIR=/
         - START_MYSQL=false
       volumes:
         - /srv/docker/owncloud/files:/usr/share/webapps/owncloud/data
         - /srv/docker/owncloud/config/:/etc/webapps/owncloud/config
     
     postgresowncloud:
       image: postgres
       environment:
         - POSTGRES_PASSWORD=owncloud
       volumes:
         - /srv/docker/owncloud/data:/var/lib/postgresql/data

**Comment by tkock** [comment]
Thanks! I have split the docker-compose files into three different versions and added your contribution for postgres.
