### ISSUE TITLE
https doesnt work out of the box

### ISSUE THREAD

**Issue by jave** [tkock/owncloud-docker-compose#3]
I tried the mysql configuration, and exposed port 80 as 8000.

I get the message "Please use https."

It would be nice with an easier out of the box https experience.

(I have an OC instance running already using the default Fedora distro packaging so I could probably manage to set https up. I'm just trying to help the default experience of the docker-compose setup.)

**Comment by tkock** [comment]
this might be part of the OC instance config.
l3iggs/docker-owncloud says: "SSL (HTTPS) encryption works out-of-the-box"
-> Can you contribute the changes necessary to the docker file?

**Comment by jave** [comment]
The below compose fragment seems to work for me.
You only need to export the https port (as 8443 in my case)
and use one of the ssl generation methods mentioned in the l3iggs/owncloud docs.
the cert self generation method is okay for a quick test.

owncloud:
  image: l3iggs/owncloud
  restart: always
  ports:
    - "8000:80"
    - "8443:443"    
  links:
    - mysql
  environment:
    VIRTUAL_HOST: myhost.mydomain,www.myhost.mydomain
    START_MYSQL: 'false'
    TARGET_SUBDIR: /
    DO_SSL_SELF_GENERATION: true
    SUBJECT: /C=SE/L=Stockholm/O=ORGANIZATION/OU=UNIT/CN=localhost
  volumes:
    # requires proper authorizations, see rights.sh
    # https://github.com/l3iggs/docker-owncloud/wiki/Store-your-data-outside-of-the-container
    - ./owncloud/volumes/data:/usr/share/webapps/owncloud/data
    - ./owncloud/volumes/config:/etc/webapps/owncloud/config

**Comment by tkock** [comment]
Thanks! I have updated the compose scripts.
